import { script } from "./example.js"

const modal = document.querySelector("#modal-pane")

document.getElementById("ico-play").onclick = runGameInBrower
document.getElementById("ico-stop").onclick = ()=> {
  document.querySelector("iframe")?.remove()
  document.querySelector("#modal-pane").style = "display: none"
}

function runGameInBrower() {
  const script = Compiler.Compile()
	const iframe = document.createElement('iframe')
	iframe.style = "border: none;"
	iframe.width = "100%"
	iframe.height = "100%"
	const html =
	`<body style="padding: 0; margin: 0; overflow: hidden; box-sizing: border-box;" > 
			<canvas id="canvas" style="background: rgb(77, 77, 77); image-rendering: pixelated" oncontextmenu="return false";></canvas> 
			<script> <!-- pre game bullshit -->
        const canvas = document.getElementById("canvas")
        const ctx = canvas.getContext("2d")

        canvas.width = 320
        canvas.height = 240
        
        canvas.style.width = "100%"
        canvas.style.height = "100%"
      </script>
      <script type="module">
        ${script}
      </script>
	</body>`

	iframe.srcdoc = html

  document.querySelector("#modal-pane").style = "display: flex"
  document.querySelector("#modal").replaceChildren()
  document.querySelector("#modal").append(iframe)
  document.querySelector("#modal").focus()
}

document.querySelector("#new-entity").onclick = () => {
  EntityManager.Create("Player")
  console.log(Game);
}

document.querySelector("#edit-entity").onclick = () => {
  EntityManager.Edit("Player", "hehehehehe")
  console.log(Game);
}





const Preferences = {}

const Game = {
  Sprite: {},
  Sound: {},
  Entity: {},
  Level: {},
  Commponent: {},

  Options: {},
}


//Game.Entity.Wall = `Create() {} \n  Update() {} \n  Render() {}`

const EntityManager = {
  Create: (name) => {
    Game.Entity[name] =
    `Create() {}
     Update() {}
     Render() {}
     Delete() {} //Flush() {}
    `
  },
  Edit: (name, code) => {
    Game.Entity[name] = code
  }
}

const Compiler = {
  Compile: () => {
    let src = "//This code is automatically generated by WebSource Game Engine"
    src += "\n" + PreGameFragment
    src += "\n" + InputFragment

    src += "\n" + SpriteFunctions
    //load sound functions here
    src += "\n" + EntityFunctions

    src += "\n" + Compiler.SpriteAssembler()
    //load soubds here
    //load components here
    src += "\n" + Compiler.EntityAssembler()
    //load maps here

    src += "\n" + GameFragment
    return src
  },
  SpriteAssembler: placeholderSpriteAssemler,
  EntityAssembler: placeholderEntityAssemler,
}

const PreGameFragment = `
const canvas = document.getElementById("canvas")
const ctx = canvas.getContext("2d")

canvas.width = 320
canvas.height = 240

canvas.style.width = "100%"
canvas.style.height = "100%"
`

const SpriteFunctions = `
//Sprite functions
function loadSprite(path) {
  let spr = new Image();
  spr.src = path;
  return spr;
};
`

const EntityFunctions = `
//EntityFunctions functions

`

const GameFragment = `
let mainArray = [] //set it to equal to the initial level

mainArray.push(new Player())

requestAnimationFrame(gameLoop) //<- make it that, this will only run when assets are loaded

function gameLoop() {
  ctx.clearRect(0, 0, canvas.width, canvas.height)
  mainArray.forEach(ent=> ent?.Update())
  mainArray.forEach(ent=> ent?.Render())
  requestAnimationFrame(gameLoop)
};
`

const InputFragment = `
let Input = {
  w: false,
  s: false,
  a: false,
  d: false
};

window.addEventListener("keydown", (event)=> {
  Input[event.key] = 1;
});

window.addEventListener("keyup", (event)=> {
  Input[event.key] = 0;
});
`

function placeholderSpriteAssemler() {
  let arr = {...Game.Sprite}
  let temp = `//Sprites \n`

  for(const key in arr) {
    temp += `const ${key} = loadSprite("${arr[key]}")` + "\n"
  }

  return temp
}

function placeholderEntityAssemler() {
  let arr = {...Game.Entity}
  let temp = `//Entitites`

for(const key in arr) {
  temp +=`
  class ${key} {
    constructor() {
      this?.Create()
    }
    ${arr[key]}
  }  
  `
  }

  return temp
}

let sprFishIdleHolder = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAAAYCAYAAAAF6fiUAAACcklEQVRoQ+1YsU7DMBC9ShUzElWH/gFzBxhgQ4Kf6F90gxE2Bv6BnygSGx0Y6IbUP+hQFYkZIQWdE6dOcvY5PpuAFC9UpHm+e+/57twB9KtTBgad7t5vDr0AHZugF+AfCJAVMaJY5ueOQ/8z24v48TkB2fp+BMfzHWxfJzA+3ZiZ+7zPMSVKgAOvmSaFgUT8+BCoNnhb7ODydgJPN5vy7+xZpe+D4eKpkgDiF7gxsBFDRJCPwBJ+OPKy6fUQVuffZRzbw4n6jEQ9nAxhdaeecTisAKkFToRf4Wf9PoKjs4NW/LiIa5BvsohCjD83MH0RiUDugdiRBE5pICs/Ov7ZHFh+nALAYk+5Ito4CRVLXwWVokoCqfHrRzCCgTKTHxu++r+DH16A/GXAUkStogTpR21KUZ5AavwishQCxzAoRZieFMDcwKxvlBAfyy81KXn0g9T4OrxUAlfjFxqIFAC7um4mWOdx6bpm66Y4IRUjKncK1FSSEr+M0SihMQ1ExR+KbyMre7zI08BGgit0A4tgKfFTC4wpNeIPNaj3CXDNkVyjqb1LEhQRnyQoooHI+EPxnT2gfgewktRuCipraCp8qkREFLh9/I5JiL0H4Lv18RMnCr3Us3YClE3SJoAQvz1Bgvgpfhpih46hJkG2MU5wEVP3AGkCDmdb8YUCkwbSmGhIE1/l5/i1gJ1YcBQ1SG7kq0QK+zmicRGznbYY+IhNmUhgINVrpPx4CWApMTmBYeSXLpImwNR2MUE++PoyWbsDmfwgDMk1L0AegatZcxiuHPaXmuYermdsTy2+8Fv4wfxIyPMlof+eg4FegI7t0QvQsQA/MkfUKBsnukYAAAAASUVORK5CYIIA"
let sprFishWalkHolder = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAAAYCAYAAAAVpXQNAAADT0lEQVRoQ+1au07dQBBdJJQaKYji/kFqCiiSLlL4Cf6CLpShS8E/8BNESpcUKUKHxB/cAhEpdYR0oxl717Prfcw+xnGw3XB9bc+Ozznz2sueWo8VgQoE9iqeXR9dEVCrgFYRVCEwJwHt+jcBn+jnqhd8YQ/PDiOugKZwfPfw+VC9uXhSjz826uh0S7nn+vkv9bJIjLjETEEurvHz9kl9+LRRXy635u/5V9QF11efiF4CufgOc8OIS4okuYDL7vjjvrp792zIfzzY4GcQ0vXJvrq7wmtcf10RSQeAOLmADxwUIzgHnACj8wul1FlVoBVhxCFEnFxXPJR9AOjo91Ydf6sSkWQAID6C5Abta5w0RhUCKg6AlIBG4pEgV90OVlEoJBNZqaQswiQDYBJyXYE2xqgqAJICEiYXyxeu0YlDabDcGtSXMP11ym99n3QAjMBvTK4p75jhujLOwSgLH1/25Ga31EKi5BqRkAz0cH+oXr995erHnP/6/gcnNWY/1PnfH/8ZuV1wad9Jj5jCqJ9gU9za4uyzfi5GoUWM45SAlOO55MJEocUCfQ4cuikMKQgmtByAJLObMLlIcAlGGVPrkEET2Y1kQEszQQGVOJ5JLgJ0876jAacIGFPbZKDZBkAGuaYM52LEDLAm2S2W5qTINcD4RBqsXfoCr5EuitwpAoBJbjlGPHyaZbesDNSIXAOOrwTE1sgc5ecXAHxyLYzoYKEnVG+vUmC/Nrsle6DYHg0lO5dcKh6sr2R0B1v0gGv0O8amojcDSQQAHbG1j423IUyz69q1RFQgnuwK4FkjWsJ8G2QxchnEmsgKbb75SHbXDDV05FlvfY9NGJkBQN0cbRX4MKrY5LMzNpkq8UK//cGcSi2/4cS3x+QGNFlnpJekgILRZPck+owzOg6AUDAGIJKJgtyQWm80xrvGaUlgCNPnWyfWwHZBhTBDONjr5Wcer4h82c0IKbJGVEAGlDi5KRJjghimpfLfueL2GSK1eozy39zouxifsAUotzkVdui71a7YnAc5TguoTuE52UTqXo5IuzLUlmgJm1IYmapgRMTkPS6gzmxNhpF+4Vb2Jf6BTcJmq/dtltmWII4pQF/sGquAFkt9mxdfBdQGx8Va+QtiNHs3f+p5ZgAAAABJRU5ErkJgggAA"

let playerplace = `
  Create() {
    this.x = 20
    this.y = 20
    this.hspeed = 0
    this.vspeed = 0
    this.health = 10
    this.speed = 1

    this.sprite = sprFishWalk
    this.prevSprite = this.sprite
    this.frame = 0
  }

  Update() {
    switch(this.sprite) {
      case sprFishWalk: {
        this.frame += 0.23
        if (this.frame > 6) this.frame = 0
        break
      }
      case sprFishIdle: {
        this.frame += 0.30
        if (this.frame > 4) this.frame = 0
        break
      }
    }

    this.hspeed = (Input.d - Input.a) * this.speed
    this.vspeed = (Input.s - Input.w) * this.speed

    this.x += this.hspeed
    this.y += this.vspeed

    this.sprite = (Input.a || Input.d || Input.w || Input.s) ? sprFishWalk : sprFishIdle
    if (this.sprite !== this.prevSprite) {this.frame = 0; this.prevSprite = this.sprite}

  }
  Render() {
    ctx.drawImage(this.sprite, 24 * Math.floor(this.frame), 0, 24, 24, Math.round(this.x), Math.round(this.y), 24, 24)
  }
`

Game.Sprite["sprFishIdle"] = sprFishIdleHolder
Game.Sprite.sprFishWalk = sprFishWalkHolder

Game.Entity.Player = playerplace


console.log(Compiler.Compile());


/*
let scroll = 100

canvas.addEventListener("wheel", (event)=> {
  if (event.deltaY > 0) scroll -= 20
  if (event.deltaY < 0) scroll += 20

  scroll = (scroll < 100) ? 100 : scroll+0
  scroll = (scroll > 500) ? 500 : scroll-0
  
  canvas.style.width = ""+scroll+"%"
  canvas.style.height = ""+scroll+"%"
})
*/

